site_name: "spec-weaver Spec"
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
extra_javascript:
    - javascripts/custom-table-filter.js
extra_css:
    - stylesheets/extra.css
nav:
  - Home: index.md
  - PLAN:
      - PLAN一覧: plan.md
      - PLAN-001: items/PLAN-001.md
      - PLAN-002: items/PLAN-002.md
      - PLAN-003: items/PLAN-003.md
  - REQ:
      - REQ一覧: req.md
      - REQ-001: items/REQ-001.md
      - REQ-002: items/REQ-002.md
      - REQ-003: items/REQ-003.md
      - REQ-004: items/REQ-004.md
      - REQ-005: items/REQ-005.md
      - REQ-006: items/REQ-006.md
      - REQ-007: items/REQ-007.md
      - REQ-008: items/REQ-008.md
      - REQ-009: items/REQ-009.md
      - REQ-010: items/REQ-010.md
      - REQ-011: items/REQ-011.md
      - REQ-012: items/REQ-012.md
  - SPEC:
      - SPEC一覧: spec.md
      - SPEC-001: items/SPEC-001.md
      - SPEC-002: items/SPEC-002.md
      - SPEC-003: items/SPEC-003.md
      - SPEC-004: items/SPEC-004.md
      - SPEC-005: items/SPEC-005.md
      - SPEC-006: items/SPEC-006.md
      - SPEC-007: items/SPEC-007.md
      - SPEC-008: items/SPEC-008.md
      - SPEC-009: items/SPEC-009.md
      - SPEC-010: items/SPEC-010.md
      - SPEC-011: items/SPEC-011.md
      - SPEC-012: items/SPEC-012.md
      - SPEC-013: items/SPEC-013.md
      - SPEC-014: items/SPEC-014.md
      - SPEC-015: items/SPEC-015.md
      - SPEC-016: items/SPEC-016.md
      - SPEC-017: items/SPEC-017.md
      - SPEC-018: items/SPEC-018.md
      - SPEC-019: items/SPEC-019.md
      - SPEC-020: items/SPEC-020.md
      - SPEC-021: items/SPEC-021.md

  - 振る舞い仕様 (Features):
      - features/index.md
      - audit.md: features/audit.md
      - build.md: features/build.md
      - ci.md: features/ci.md
      - data_extraction.md: features/data_extraction.md
      - impl_link.md: features/impl_link.md
      - scaffold.md: features/scaffold.md
      - status.md: features/status.md
      - timestamp.md: features/timestamp.md
      - trace.md: features/trace.md

markdown_extensions:
  - tables
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
